sudo: false
language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"
  - "pypy3"

before_install:
  - python setup.py sdist bdist_wheel --universal

install:
  - pip install tox-travis
  - pip install coveralls
  - pip install -U dist/*.whl

env:
  - NAME=pynogram

before_script:
  # docs and LICENSE should be in sources
  - tar -tf dist/*.tar.gz | grep -v "/$NAME" | grep '/LICENSE'
  - tar -tf dist/*.tar.gz | grep -v "/$NAME" | grep '/docs/.\+md'

  # only two files should left
  - pip show -f $NAME | grep '^ ' | grep -v " $NAME[-/]" |
    wc -l | exit $(awk '{print $1-2}')

script:
  - tox
  - time $NAME -b winter -v
  - time $NAME --pbn 4089 --draw-final -vv

  - tox -e lint -- $NAME --output-format=text | tee pylint.log || true
  # fail if pylint gets score < 9.5
  - grep -oP 'has been rated at \K([^/]+)' pylint.log |
    python -c 'import sys; a=int((10-float(sys.stdin.read()))*100); sys.exit(a if a>50 else 0)'


after_success: coveralls
